# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ptu_state.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ptu_state.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0fptu_state.proto\"\x16\n\x07\x44\x65grees\x12\x0b\n\x03\x64\x65g\x18\x01 \x01(\x01\"\"\n\x0f\x41ngularVelocity\x12\x0f\n\x07\x64\x65g_sec\x18\x01 \x01(\x01\"\xb2\x01\n\x08PtuState\x12\x1e\n\x0cpan_position\x18\x01 \x01(\x0b\x32\x08.Degrees\x12&\n\x0cpan_velocity\x18\x02 \x01(\x0b\x32\x10.AngularVelocity\x12\x1f\n\rtilt_position\x18\x03 \x01(\x0b\x32\x08.Degrees\x12\'\n\rtilt_velocity\x18\x04 \x01(\x0b\x32\x10.AngularVelocity\x12\x14\n\x0ctimestamp_ms\x18\x05 \x01(\x04\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DEGREES = _descriptor.Descriptor(
  name='Degrees',
  full_name='Degrees',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='deg', full_name='Degrees.deg', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=41,
)


_ANGULARVELOCITY = _descriptor.Descriptor(
  name='AngularVelocity',
  full_name='AngularVelocity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='deg_sec', full_name='AngularVelocity.deg_sec', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=77,
)


_PTUSTATE = _descriptor.Descriptor(
  name='PtuState',
  full_name='PtuState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pan_position', full_name='PtuState.pan_position', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pan_velocity', full_name='PtuState.pan_velocity', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tilt_position', full_name='PtuState.tilt_position', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tilt_velocity', full_name='PtuState.tilt_velocity', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp_ms', full_name='PtuState.timestamp_ms', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=258,
)

_PTUSTATE.fields_by_name['pan_position'].message_type = _DEGREES
_PTUSTATE.fields_by_name['pan_velocity'].message_type = _ANGULARVELOCITY
_PTUSTATE.fields_by_name['tilt_position'].message_type = _DEGREES
_PTUSTATE.fields_by_name['tilt_velocity'].message_type = _ANGULARVELOCITY
DESCRIPTOR.message_types_by_name['Degrees'] = _DEGREES
DESCRIPTOR.message_types_by_name['AngularVelocity'] = _ANGULARVELOCITY
DESCRIPTOR.message_types_by_name['PtuState'] = _PTUSTATE

Degrees = _reflection.GeneratedProtocolMessageType('Degrees', (_message.Message,), dict(
  DESCRIPTOR = _DEGREES,
  __module__ = 'ptu_state_pb2'
  # @@protoc_insertion_point(class_scope:Degrees)
  ))
_sym_db.RegisterMessage(Degrees)

AngularVelocity = _reflection.GeneratedProtocolMessageType('AngularVelocity', (_message.Message,), dict(
  DESCRIPTOR = _ANGULARVELOCITY,
  __module__ = 'ptu_state_pb2'
  # @@protoc_insertion_point(class_scope:AngularVelocity)
  ))
_sym_db.RegisterMessage(AngularVelocity)

PtuState = _reflection.GeneratedProtocolMessageType('PtuState', (_message.Message,), dict(
  DESCRIPTOR = _PTUSTATE,
  __module__ = 'ptu_state_pb2'
  # @@protoc_insertion_point(class_scope:PtuState)
  ))
_sym_db.RegisterMessage(PtuState)


# @@protoc_insertion_point(module_scope)
