// Generated by gencpp from file seervision/AddTwoInts.msg
// DO NOT EDIT!


#ifndef SEERVISION_MESSAGE_ADDTWOINTS_H
#define SEERVISION_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <seervision/AddTwoIntsRequest.h>
#include <seervision/AddTwoIntsResponse.h>


namespace seervision
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace seervision


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::seervision::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::seervision::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::seervision::AddTwoInts > {
  static const char* value()
  {
    return "seervision/AddTwoInts";
  }

  static const char* value(const ::seervision::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::seervision::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::seervision::AddTwoInts >
template<>
struct MD5Sum< ::seervision::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::seervision::AddTwoInts >::value();
  }
  static const char* value(const ::seervision::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::seervision::AddTwoIntsRequest> should match
// service_traits::DataType< ::seervision::AddTwoInts >
template<>
struct DataType< ::seervision::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::seervision::AddTwoInts >::value();
  }
  static const char* value(const ::seervision::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::seervision::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::seervision::AddTwoInts >
template<>
struct MD5Sum< ::seervision::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::seervision::AddTwoInts >::value();
  }
  static const char* value(const ::seervision::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::seervision::AddTwoIntsResponse> should match
// service_traits::DataType< ::seervision::AddTwoInts >
template<>
struct DataType< ::seervision::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::seervision::AddTwoInts >::value();
  }
  static const char* value(const ::seervision::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SEERVISION_MESSAGE_ADDTWOINTS_H
