// Generated by gencpp from file seervision/Num.msg
// DO NOT EDIT!


#ifndef SEERVISION_MESSAGE_NUM_H
#define SEERVISION_MESSAGE_NUM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace seervision
{
template <class ContainerAllocator>
struct Num_
{
  typedef Num_<ContainerAllocator> Type;

  Num_()
    : first_name()  {
    }
  Num_(const ContainerAllocator& _alloc)
    : first_name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _first_name_type;
  _first_name_type first_name;





  typedef boost::shared_ptr< ::seervision::Num_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::seervision::Num_<ContainerAllocator> const> ConstPtr;

}; // struct Num_

typedef ::seervision::Num_<std::allocator<void> > Num;

typedef boost::shared_ptr< ::seervision::Num > NumPtr;
typedef boost::shared_ptr< ::seervision::Num const> NumConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::seervision::Num_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::seervision::Num_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::seervision::Num_<ContainerAllocator1> & lhs, const ::seervision::Num_<ContainerAllocator2> & rhs)
{
  return lhs.first_name == rhs.first_name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::seervision::Num_<ContainerAllocator1> & lhs, const ::seervision::Num_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace seervision

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::seervision::Num_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::seervision::Num_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::seervision::Num_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::seervision::Num_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::seervision::Num_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::seervision::Num_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::seervision::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "80e8c9c65232d3c1560d7601e9eb9de8";
  }

  static const char* value(const ::seervision::Num_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x80e8c9c65232d3c1ULL;
  static const uint64_t static_value2 = 0x560d7601e9eb9de8ULL;
};

template<class ContainerAllocator>
struct DataType< ::seervision::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "seervision/Num";
  }

  static const char* value(const ::seervision::Num_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::seervision::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string first_name\n"
;
  }

  static const char* value(const ::seervision::Num_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::seervision::Num_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.first_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Num_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::seervision::Num_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::seervision::Num_<ContainerAllocator>& v)
  {
    s << indent << "first_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.first_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEERVISION_MESSAGE_NUM_H
